version: '3.8'  # You can remove this line in Docker Compose v2.x

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_container
    ports:
      - "1433:1433"  # Expose port 1433
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"  # Set a strong password
      ACCEPT_EULA: "Y"  # Accept the EULA
      MSSQL_PID: "Express"  # Use SQL Server Express
    volumes:
      - mssql_data:/var/opt/mssql  # Persist data
    restart: always

volumes:
  mssql_data:
