services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Adjust if your Dockerfile is named differently
    ports:
      - "8080:8080"  # Change as needed
    environment:
      - PORT=8080
    restart: unless-stopped
